### ISSUE TITLE
Getting Null Pointer Exception everytime for my field id

### ISSUE THREAD

**Issue by fatmali** [MacroYau/ThingSpeakAndroid#1]
Hi there,
Great library. However I keep getting an error with just my channels. With other channels the library works well. What could I be doing wrong? Here is the error:

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
                                                                             at java.lang.StringToReal.parseFloat(StringToReal.java:304)
                                                                             at java.lang.Float.parseFloat(Float.java:306)
                                                                             at com.macroyau.thingspeakandroid.ThingSpeakLineChart.onChannelFieldFeedUpdated(ThingSpeakLineChart.java:124)
                                                                             at com.macroyau.thingspeakandroid.ThingSpeakChannel$4.success(ThingSpeakChannel.java:375)
                                                                             at com.macroyau.thingspeakandroid.ThingSpeakChannel$4.success(ThingSpeakChannel.java:371)
                                                                             at retrofit.CallbackRunnable$1.run(CallbackRunnable.java:45)
                                                                             at android.os.Handler.handleCallback(Handler.java:739)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                             at android.os.Looper.loop(Looper.java:135)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5753)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

**Comment by Davo-Exp4** [comment]
Hey man, do you solve the problem, i have the same issue please help

**Comment by MacroYau** [comment]
@Davo-Exp4 The current version of the library could not handle non-numeric values (hence the parsing error) in the feed. I am working on a patch to ignore these data points.

**Comment by Davo-Exp4** [comment]
@MacroYau Thanks for your help and your hard work, please keep me updated with your progress you helped me a lot, if you want to do some tests here is my Channel ID: 396520. 
Greetings from Ecuador.

**Comment by MacroYau** [comment]
The problem should have been fixed. Please update to `v0.2.2`. Thanks!
